passagens/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('minha_consulta', views.revisao_consulta, name="minha_consulta"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('passagens.urls')),
]

passagens/models.py
from django.db import models

# Create your models here.

passagens/models/classe_viagem.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class ClasseViagem(models.TextChoices):
        ECONOMICA = 'ECON', _('Econômica')
        EXECUTIVA = 'EXEC', _('Executiva')
        PRIMEIRA_CLASSE = 'PRIC', _('Primeira Classe')

passagens/models/passagem.py
from django.db import models
from .classe_viagem import ClasseViagem

class Passagem(models.Model):
    origem = models.CharField(max_length=100)
    destino = models.CharField(max_length=100)
    data_ida = models.DateField()
    data_volta = models.DateField()
    data_pesquisa = models.DateField()
    informacoes = models.TextField(max_length=200, blank=True)
    classe_viagem = models.CharField(max_length=4,choices=ClasseViagem.choices, default=0)

passagens/models/pessoa.py
from django.db import models

class Pessoa(models.Model):
    nome = models.CharField(max_length=200)
    email = models.EmailField()

passagens/forms.py
from django import  forms
from tempus_dominus.widgets import DatePicker
from passagens.classe_viagem import  tipos_de_classes
from datetime import datetime
from passagens.validation import *
from passagens.models import  Passagem, ClasseViagem, Pessoa

class PassagemForms(forms.ModelForm):
    """Classe dos campos da passagem"""
    data_pesquisa = forms.DateField(label="Data da pesquisa", disabled=True, initial=datetime.today())

    class Meta:
        model = Passagem
        fields = '__all__'
        labels = {'data_ida':'Data de ida', 'data_volta': 'Data de volta', 'informacoes':'Informações','classe_viagem':"Classe do vôo"}
        widgets = { 'data_ida':DatePicker(), 'data_volta': DatePicker()}
        data_pesquisa = forms.DateField(label="Data da pesquisa", disabled=True, initial=datetime.today())

    def clean(self):
        origem = self.cleaned_data.get('origem')
        destino = self.cleaned_data.get('destino')
        data_ida = self.cleaned_data.get('data_ida')
        data_volta = self.cleaned_data.get('data_volta')
        data_pesquisa = self.cleaned_data.get('data_pesquisa')

        lista_de_erros = {}

        campo_tem_algum_numero(origem, 'origem', lista_de_erros)
        campo_tem_algum_numero(destino, 'destino', lista_de_erros)
        origem_destino_iguais(origem, destino, lista_de_erros)
        data_ida_maior_que_data_volta(data_ida, data_volta, lista_de_erros)
        data_ida_menor_data_de_hoje(data_ida, data_pesquisa, lista_de_erros)

        if lista_de_erros is not None:
            for erro in lista_de_erros:
                mensagem_erro = lista_de_erros[erro]
                self.add_error(erro,mensagem_erro)
        return self.cleaned_data

class PessoaForms(forms.ModelForm):
    class Meta:
        model = Pessoa
        exclude = ['nome']

passagens/views.py
from django.shortcuts import render
from passagens.forms import PassagemForms, PessoaForms
# Create your views here.
def index(request):
    form = PassagemForms()
    pessoa_form = PessoaForms()
    contexto = {'form':form, 'pessoa_form': pessoa_form}
    return render(request, 'index.html', contexto)


def revisao_consulta(request):
    if request.method == 'POST':
        form = PassagemForms(request.POST)
        pessoa_form = PessoaForms(request.POST)
        if form.is_valid():
            contexto = {'form':form, 'pessoa_form': pessoa_form}
            return render(request, 'minha_consulta.html', contexto)
        else:
            print("Form invalid")
            contexto = {'form':form, 'pessoa_form': pessoa_form}
            return render(request, 'index.html', contexto)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>


    {{ form.media }}
    <title>Passagem</title>
        <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <section class="container mt-4" align = 'center' id="form">
      <nav class="navbar-bottom">
        <a class="navbar-brand" href="{% url 'index' %}">Passagem</a>
      </nav>

      {% block content %}{% endblock %}
    </section>

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load widget_tweaks %}
<section class=" container col-8">
    <form action="{% url 'minha_consulta' %}" method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            {{field|add_class:'form-control'}}
        </div>
        {% for error in field.errors %}
        <section class="alert alert-danger">
            {{ field.errors }}
        </section>
        {% endfor %}
        {% endfor %}
        {% for field in pessoa_form.visible_fields %}
        <div class="form-group">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            {{field|add_class:'form-control'}}
        </div>
        {% endfor %}
        <input type="submit" value="Ok" class="btn btn-success">
    </form>
</section>



{% endblock %}

templates/minha_consulta.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p>Sua Origem é: {{ form.origem.value }}</p>
<p>Ser Destino é: {{ form.destino.value }}</p>
<p>Sua Data de Ida é: {{ form.data_ida.value }}</p>
<p>Sua Data de volta é: {{ form.data_volta.value }}</p>
<p>Pesquisa realizada: {{ form.data_pesquisa.value }}</p>
<p>Classe de vôo: {{ form.instance.get_classe_viagem_display }}</p>
<p>Informações extras: {{ form.informacoes.value }}</p>
<p>Seu Email é: {{ pessoa_form.email.value }}</p>
{% endblock %}